feat: add Command line support
ManemDhanush/discord-storage-system pull request #1
Opened 2024-02-04 22:57 UTC by ManemDhanush

Before: 
- we had only the index.js as the only file to upload and download the files

After:
- created support for CLI
- can upload a messages with `node src/index.js -u "Message" "Title"`
- can download all messages with `node src/index.js -u "Title"`

Thoughts:
- Should we have both CLI and index.js support??

2024-02-06 05:04 UTC, QuickHawk requested changes
Update the PR description with the proper flag used for download.

2024-02-06 05:04 UTC, QuickHawk commented on src/index.js
> -require('dotenv').config();
Why remove this?

Put this back...... invoking this only once at the `index.js` make lot of sense

2024-02-06 05:04 UTC, QuickHawk commented on src/api/discord/upload.js
Client creation is for each request? Why???

2024-02-06 05:04 UTC, QuickHawk commented on src/api/discord/download.js
Redundant creation of Client object? Use Singleton Design Pattern or something.......

I'm assuming since we will push into only on one discord server why do we need to create Client for each request.

2024-02-08 01:27 UTC, ManemDhanush commented on src/api/discord/download.js
I'd agree we if we are using both the upload and download in a single run
But through CLI only one of the file is called `upload.js` or `download.js` not both at once so I guess Singleton will be used in the future when we create a website

2024-02-08 01:27 UTC, ManemDhanush commented on src/api/discord/upload.js
https://github.com/ManemDhanush/discord-storage-system/pull/1#discussion_r1482306751

2024-02-10 20:28 UTC, QuickHawk approved these changes

2024-02-14 03:31 UTC, merged